version: 2
updates:
  # Enable version updates for npm (backend)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "sabady"
    assignees:
      - "sabady"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "auto-merge"
    # Auto-merge settings
    pull-request-branch-name:
      separator: "/"
    # Group updates by dependency type
    groups:
      # Group all TypeScript-related updates
      typescript:
        patterns:
          - "typescript"
          - "@types/*"
          - "ts-*"
      # Group all testing-related updates
      testing:
        patterns:
          - "jest"
          - "@types/jest"
          - "supertest"
          - "@types/supertest"
          - "testcontainers"
          - "mongodb-memory-server"
      # Group all security-related updates
      security:
        patterns:
          - "helmet"
          - "cors"
          - "express-rate-limit"
      # Group all Kafka-related updates
      kafka:
        patterns:
          - "kafkajs"
      # Group all MongoDB-related updates
      mongodb:
        patterns:
          - "mongoose"
      # Group all monitoring-related updates
      monitoring:
        patterns:
          - "prom-client"
          - "@types/prom-client"

  # Enable version updates for npm (frontend)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "sabady"
    assignees:
      - "sabady"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "frontend"
      - "auto-merge"
    # Group updates by dependency type
    groups:
      # Group all React-related updates
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      # Group all Material-UI updates
      material-ui:
        patterns:
          - "@mui/*"
          - "@material-ui/*"
      # Group all frontend testing updates
      frontend-testing:
        patterns:
          - "@testing-library/*"
          - "web-vitals"
      # Group all frontend utilities
      frontend-utils:
        patterns:
          - "axios"
          - "uuid"
          - "@types/uuid"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "sabady"
    assignees:
      - "sabady"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
      - "auto-merge"
    # Group Docker updates
    groups:
      # Group all base image updates
      base-images:
        patterns:
          - "node"
          - "alpine"
      # Group all service updates
      services:
        patterns:
          - "mongo"
          - "kafka"
          - "prometheus"
          - "metrics-server"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "sabady"
    assignees:
      - "sabady"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "auto-merge"
    # Group GitHub Actions updates
    groups:
      # Group all Node.js setup actions
      node-actions:
        patterns:
          - "actions/setup-node"
      # Group all Docker actions
      docker-actions:
        patterns:
          - "docker/*"
      # Group all artifact actions
      artifact-actions:
        patterns:
          - "actions/upload-artifact"
          - "actions/download-artifact"
      # Group all Kubernetes actions
      k8s-actions:
        patterns:
          - "azure/setup-kubectl"