apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: default
  labels:
    app: kafka
spec:
  type: ClusterIP
  ports:
  - port: 9092
    targetPort: 9092
    protocol: TCP
    name: kafka
  - port: 9101
    targetPort: 9101
    protocol: TCP
    name: jmx
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service-nodeport
  namespace: default
  labels:
    app: kafka
spec:
  type: NodePort
  ports:
  - port: 9092
    targetPort: 9092
    protocol: TCP
    name: kafka
    nodePort: 30092
  - port: 9101
    targetPort: 9101
    protocol: TCP
    name: jmx
    nodePort: 30101
  selector:
    app: kafka
