apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: default
type: Opaque
data:
  # Base64 encoded values - replace with your actual credentials
  # To encode: echo -n "your-username" | base64
  # To encode: echo -n "your-password" | base64
  username: bW9uZ29kYg==  # mongodb
  password: bW9uZ29kYjEyMw==  # mongodb123
  root-username: YWRtaW4=  # admin
  root-password: YWRtaW4xMjM=  # admin123
