apiVersion: v1
kind: Service
metadata:
  name: api-server-service
  namespace: default
  labels:
    app: api-server
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: api-server
---
apiVersion: v1
kind: Service
metadata:
  name: api-server-service-nodeport
  namespace: default
  labels:
    app: api-server
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
    nodePort: 30080
  selector:
    app: api-server
