apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
  namespace: default
  labels:
    app: api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: api-server
        image: ghcr.io/sabady/mongo-kafka-api-frontend/api-server:latest
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: MONGODB_URI
          value: "mongodb://admin:admin123@mongodb-service:27017/admin?authSource=admin"
        - name: MONGODB_DATABASE
          value: "api_db"
        - name: KAFKA_BROKERS
          value: "kafka-service:9092"
        - name: KAFKA_CLIENT_ID
          value: "api-server"
        - name: CORS_ORIGIN
          value: "*"
        - name: API_RATE_LIMIT_WINDOW_MS
          value: "900000"
        - name: API_RATE_LIMIT_MAX_REQUESTS
          value: "1000"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 10
